### ISSUE TITLE
getting started with the winforms radpdfviewer video link broken.

### ISSUE THREAD

**Issue by bruceburge** [telerik/winforms-docs#20]
The following link 
http://tv.telerik.com/watch/radcontrols-for-winforms/getting-started-with-the-winforms-radpdfviewer
on http://docs.telerik.com/devtools/winforms/pdfviewer/getting-started

Is Broken, it redirects to the base video page.

**Comment by icom85** [comment]
Hi Bruce,

Thank you for submitting the issue. The link will be updated as soon as the video is reuploaded.

**Comment by bruceburge** [comment]
@icom85 do you work for telerik?

**Comment by icom85** [comment]
@bruceburge Yes I do.

**Comment by bruceburge** [comment]
what is the best method to resolve these issues, waiting two weeks, to hear that something broken will be updated at some point from a company we are paying for support seems a bit unprofessional, and certainly not acceptable.

**Comment by icom85** [comment]
This is the proper place to post issues related to the documentation similar to the one you have submitted. At the moment I cannot give you an estimate when it will be fixed. If you have technical questions you can use the ticketing system or the forums here: http://www.telerik.com/forums/winforms.

**Comment by icom85** [comment]
Hi Bruce,

The RadPdfViewer getting started video is now available on our YouTube channel: https://www.youtube.com/watch?v=CmoZmSdvKic&feature=youtu.be. The pages on our Telerik video site should be soon fixed as well.

**Comment by icom85** [comment]
The link is now working: http://tv.telerik.com/watch/radcontrols-for-winforms/getting-started-with-the-winforms-radpdfviewer
