### ISSUE TITLE
Where do you get the installer?

### ISSUE THREAD

**Issue by awerber** [telerik/winforms-docs#32]
https://docs.telerik.com/devtools/winforms/installation-deployment-and-distribution/installing-on-your-computer is missing the most critical piece of information - the location of the installer program!

**Comment by icom85** [comment]
Hi,
You can download the installer straight from your Telerik account: www.telerik.com/account. Once in your account, you should navigate to the Download tab: https://docs.telerik.com/devtools/winforms/installation-deployment-and-distribution/download-product-files.
