### ISSUE TITLE
winforms-docs/gridview/hierarchical-grid/ uses wrong image in Manually generating hierarchy mode

### ISSUE THREAD

**Issue by bruceburge** [telerik/winforms-docs#40]
The text says 

> The following example demonstrates how you can manually build an object-relational hierarchy using the "Customers" entity model from the Northwind  database:

But the image is of the Product and Suppliers relationship, not customer and orders.
[image used](https://docs.telerik.com/devtools/winforms/gridview/hierarchical-grid/images/gridview-hierarchical-grid-object-relational-hierarchy-mode003.png)

Without standing up a instance of the northwind database, making sense of this example is guess work.

**Comment by dessyordanova** [comment]
Fixed in R2 2021
