### ISSUE TITLE
Update VS Extensions Options dialog documentation article

### ISSUE THREAD

**Issue by YanaTacheva** [telerik/winforms-docs#408]
Hey guys,

We have removed the **VS Extensions Options** menu from the **Extensions** -> **Telerik** and add a new **Options** menu under the **Extensions** -> **Telerik** -> **Telerik UI for WinForms** menu, as it is shown below. Could you please update it in this [documentation article](https://docs.telerik.com/devtools/winforms/visual-studio-integration/visual-studio-extensions/options)?

**New screenshot:**
![winforms-options-menu](https://github.com/telerik/winforms-docs/assets/17295287/43667b38-e2dd-413a-a9e6-30d97dea4234)

**Comment by dessyordanova** [comment]
The image is updated and it will be released with R2 2023 SP1 on Wednesday
