### ISSUE TITLE
Typo in How-To article (Create Printable Panel)

### ISSUE THREAD

**Issue by ergonzalez-boh** [telerik/winforms-docs#436]
There's a typo in both the URL and the list item. The word prinatble should be printable

- https://docs.telerik.com/devtools/winforms/telerik-presentation-framework/printing-support/how-to/create-prinatble-panel
- Create Prinatble Panel 

![image](https://github.com/telerik/winforms-docs/assets/137728341/f7cbe8cc-7f3b-49f8-ad0e-15ab265c6838)
![image](https://github.com/telerik/winforms-docs/assets/137728341/dc838791-59f9-4f4a-90d1-c04423dc1b0a)

**Comment by DinkoK** [comment]
Thank you for pointing this out to us. I have fixed the typo in the navigation tree. The update will be live pretty soon.
