### ISSUE TITLE
gridview/context-menus/modifying-the-default-context-menu.md example is not safe for localization

### ISSUE THREAD

**Issue by urosjovanovic** [telerik/winforms-docs#45]
In the example code for removing items from default RadGridView context menu it uses the hard coded string "Conditional Formatting".  What if the application is localized to another language? 

Shouldn't we use:
`RadGridLocalizationProvider.CurrentProvider.GetLocalizedString(RadGridStringId.ConditionalFormattingCaption)`

https://docs.telerik.com/devtools/winforms/controls/gridview/context-menus/modifying-the-default-context-menu

**Comment by DKaramfilov** [comment]
Hi,

You are right. I have added a note for this under the example.

Regards,
Dimitar
