### ISSUE TITLE
Update documentation with Toolbox Configuration step in New Project Wizard

### ISSUE THREAD

**Issue by nikolavn** [telerik/winforms-docs#463]
As a result of [this issue](https://github.com/telerik/vsx/issues/453) a new step, that allows clients to configure the toolbox, was added to the new project wizard.

Please update the documentation accordingly. You can use [the specification](https://github.com/telerik/vs-extensions/blob/develop/docs/Telerik%20WinForms%20VS%20Extensions.md#toolbox-configuration-option) as a reference.

**Comment by dessyordanova** [comment]
It is added to the respective article and it will be live for the service pack: https://testdocs.telerik.com/devtools/winforms/visual-studio-integration/visual-studio-extensions/create-project
