### ISSUE TITLE
PdfViewer Exception Handling article

### ISSUE THREAD

**Issue by YoanKar** [telerik/winforms-docs#528]
Refactor the WinForms "PdfViewer Exception Handling article (https://docs.telerik.com/devtools/winforms/controls/pdfviewer/exception-handling)" to reference the "DPL Exception Handling" one instead (https://github.com/telerik/document-processing-docs/blob/master/libraries/radpdfprocessing/features/handling-document-exceptions.md).

We are striving to unify this article for all products. Each product can reference this DPL article instead of having its own and needing to manually update it after each change. This will be the sole article that will list all exceptions and the DPL team will be responsible for its maintenance.

Potential reference from WPF - https://docs.telerik.com/devtools/wpf/controls/radpdfviewer/document-model/exceptionhandling

**Comment by DinkoK** [comment]
Thank you for sharing this. The article is updated.
