### ISSUE TITLE
No gems for bundler

### ISSUE THREAD

**Issue by fakoor** [telerik/winforms-docs#54]
There should be some steps in "running locally" section between steps one and two. That is, after cloning the repository,  issuing the bundle install, requires some gem file that does not exist or have not been created yet.

**Comment by dessyordanova** [comment]
You can find full instructions for local setup in the main docs repo: https://github.com/telerik/docs-seed#readme
However, I would recommend you to use the online documentation with the same content like this repo: https://docs.telerik.com/devtools/winforms/introduction
