### ISSUE TITLE
Document "Automatically Populate Toolbox" option

### ISSUE THREAD

**Issue by nikolavn** [telerik/winforms-docs#579]
The ***Automatically Populate Toolbox*** affects whether controls are populated in the .NET Core designer. If set to **false** the WinForms controls are not visible in the designer.

It's worthwhile to add information about this in the respective section of the documentation. 

More information is available in the [Developer Community](https://developercommunity.visualstudio.com/t/Custom-controls-are-not-loaded-to-Toolbo/10055735) and in ticket: **1654663**

**Comment by nade7o** [comment]
Thank you for pointing this to our attention. I have already added it to the respective article and will be live in our documentation very soon: https://testdocs.telerik.com/devtools/winforms/core/core-toolbox-version#troubleshooting-visual-studio-toolbox
